In [1]:
from LPMD import *
import pandas as pd
import numpy as np

In [2]:
def model_lpmd(
        datamissing,
        datacomplete,
        target
    ):
        imputer = LPMD(datacomplete, 
                                              iteracoes=1000, 
                                              epsilon=1e-256)
        
        model = imputer.fit(datamissing, target)
        
        return model

In [3]:
from sklearn.datasets import load_iris

# Carregar o dataset Iris
iris = load_iris()

# Converter para um DataFrame do pandas
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Adicionar a coluna de target
iris_df['target'] = iris.target

# Exibir o DataFrame
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [4]:
from sklearn.datasets import load_iris

# Carregar o dataset Iris
iris = load_iris()

# Converter para um DataFrame do pandas
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Adicionar a coluna de target ao DataFrame iris_df
iris_df['target'] = iris.target

# Filtrar as primeiras 5 linhas da classe setosa (target == 0)
iris_setosa = iris_df[iris_df['target'] == 0].head(5)
print(iris_setosa)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [5]:
# Data with missing data (Dataset Iris, setosa class example)
data = [
    [5.1, np.nan, 1.4, 0.2],
    [4.9, 3.0, 1.4, np.nan],
    [4.7, 3.2, np.nan, 0.2],
    [np.nan, 3.1, 1.5, 0.2],
    [5.0, 3.6, np.nan, 0.2]
]

# Define the column names
columns = ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]

# Create the DataFrame
X = pd.DataFrame(data, columns=columns)

# Display the DataFrame
print(X)

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         NaN          1.4         0.2
1          4.9         3.0          1.4         NaN
2          4.7         3.2          NaN         0.2
3          NaN         3.1          1.5         0.2
4          5.0         3.6          NaN         0.2


In [6]:
# Replace NaN values with -1
X_linha = X.copy()
X_linha.fillna(-1, inplace=True)
print(X_linha)

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1        -1.0          1.4         0.2
1          4.9         3.0          1.4        -1.0
2          4.7         3.2         -1.0         0.2
3         -1.0         3.1          1.5         0.2
4          5.0         3.6         -1.0         0.2


In [ ]:
# Make class, example: imputer = LPMD(datacomplete, iteracoes=1000, epsilon=1e-32)
imputer = LPMD(X_linha, iteracoes=10000, epsilon=1e-32)

max iterations:  10000
epsilon:  1e-32


In [25]:
# Training model, example: model = imputer.fit(datamissing, target)
model = imputer.fit(X.values[:], [0, 0, 0, 0, 0])

Number of clusters:  1
Imputed:
0        0
1        0
2        0
3        0
grupo    0
dtype: int64
Dif:  42.70000000000001
Iteration:  1
Y:  [[ 5.1        -0.93339344  1.4         0.2       ]
 [ 4.9         3.          1.4        -0.70532766]
 [ 4.7         3.2        -0.81197371  0.2       ]
 [-0.99881183  3.1         1.5         0.2       ]
 [ 5.          3.6        -0.82566661  0.2       ]]
Dif:  0.724826749351144
Iteration:  2
Y:  [[ 5.1        -0.8678752   1.4         0.2       ]
 [ 4.9         3.          1.4        -0.48301515]
 [ 4.7         3.2        -0.64479092  0.2       ]
 [-0.99762391  3.1         1.5         0.2       ]
 [ 5.          3.6        -0.65784574  0.2       ]]
Dif:  0.6240223324118229
Iteration:  3
Y:  [[ 5.1        -0.80342752  1.4         0.2       ]
 [ 4.9         3.          1.4        -0.31529376]
 [ 4.7         3.2        -0.49042089  0.2       ]
 [-0.99643623  3.1         1.5         0.2       ]
 [ 5.          3.6        -0.50250173  0.2       ]]
Dif: 

In [ ]:
# Imputing missing values
output = model.transform(X.iloc[:, :].values)
print(output)